/**
 * Bundle the MCP App views into self-contained HTML and emit the COMPLETE
 * src/ui/register.ts module (committed).
 *
 * Why the whole module is generated: register.ts is imported as a VALUE by
 * both runtimes — node dist (stdio server, needs `.js` import specifiers)
 * and the Next.js remote endpoint (bundler, resolves extensionless .ts).
 * Files on that dual path must have no relative value imports of their own
 * (the same invariant that keeps seller-tools' api-client import type-only),
 * so the HTML is inlined here instead of imported from a sibling module.
 *
 * Run: npm run build:ui   (from mcp-server/)
 */
import { build } from 'esbuild'
import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))

const BASE_CSS = `
  *{box-sizing:border-box;margin:0;padding:0}
  body{font-family:system-ui,-apple-system,sans-serif;color:#1F2937;background:transparent;padding:12px}
  .head{font-size:13px;font-weight:600;color:#6B7280;margin-bottom:10px}
  .empty,.error{padding:20px;text-align:left;color:#6B7280;font-size:14px}
  .error{color:#DC2626}
  .grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(150px,1fr));gap:10px}
  .card{border:1px solid #E5E7EB;background:#fff;overflow:hidden}
  .card img{width:100%;height:96px;object-fit:cover;display:block}
  .card .ph{width:100%;height:96px;background:#F3F4F6}
  .card .body{padding:8px 10px}
  .row{display:flex;align-items:center;justify-content:space-between;gap:6px}
  .price{color:#2563EB;font-weight:700;font-size:14px}
  .title{font-size:13px;font-weight:500;margin-top:2px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
  .meta{font-size:11px;color:#9CA3AF;margin-top:2px}
  .queue{margin-left:6px;color:#A16207}
  .publish{padding:20px;text-align:left}
  .check{width:36px;height:36px;border-radius:9999px;background:#DCFCE7;color:#166534;display:flex;align-items:center;justify-content:center;font-size:20px;font-weight:700;margin-bottom:10px}
  .msg{font-size:15px;font-weight:600;margin-bottom:8px}
  .url{color:#2563EB;font-size:14px;word-break:break-all;text-decoration:underline}
  .hint{font-size:12px;color:#9CA3AF;margin-top:10px}
  .res{border:1px solid #E5E7EB;background:#fff;padding:10px 12px;margin-bottom:8px}
  .buyer{font-weight:600;font-size:13px}
  .unread{background:#2563EB;color:#fff;border-radius:9999px;font-size:10px;font-weight:700;padding:1px 6px;margin-left:6px}
  .items{font-size:12px;color:#4B5563;margin-top:3px}
  .last{font-size:12px;color:#9CA3AF;font-style:italic;margin-top:3px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
  .pickup{font-size:12px;color:#166534;margin-top:3px}
`

// One combined view: the ext-apps runtime (~400KB incl. protocol schema)
// would be duplicated per view otherwise. views/app.ts dispatches on the
// tool payload shape.
const VIEWS = [{ key: 'app', entry: 'views/app.ts', title: 'ClearList' }]

async function bundleView(entry) {
  const result = await build({
    entryPoints: [join(__dirname, entry)],
    bundle: true,
    format: 'iife',
    platform: 'browser',
    target: 'es2020',
    minify: true,
    write: false,
  })
  return result.outputFiles[0].text
}

const parts = []
for (const view of VIEWS) {
  const js = await bundleView(view.entry)
  const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${view.title}</title>
<style>${BASE_CSS}</style>
</head>
<body>
<div id="root">Loading…</div>
<script>${js}</script>
</body>
</html>`
  parts.push(`  ${view.key}: ${JSON.stringify(html)},`)
}

const out = `/**
 * AUTO-GENERATED by src/ui/build-ui.mjs — DO NOT EDIT BY HAND.
 * Regenerate after changing src/ui/views/*: npm run build:ui
 *
 * MCP Apps (SEP-1865) wiring: the ui:// view resource, self-contained
 * bundled HTML, and the registration helper. Committed so both the tsc
 * build (node stdio server) and the Next.js remote endpoint can import it
 * with no runtime fs read and no esbuild step.
 *
 * IMPORTANT: this module is value-imported by BOTH the node dist and the
 * Next.js bundler, so it must contain no relative value imports (type-only
 * imports are fine — they're erased before either resolver runs). The tool
 * _meta that references UI_APP_RESOURCE_URI lives as a literal in
 * seller-tools.ts for the same reason; keep the URI in sync.
 */
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'

/** Spec mime type for MCP App views (ext-apps RESOURCE_MIME_TYPE). */
export const UI_RESOURCE_MIME_TYPE = 'text/html;profile=mcp-app'

/** The single ClearList app view, shared by all UI-enabled tools. */
export const UI_APP_RESOURCE_URI = 'ui://clearlist/app.html'

const UI_VIEW_HTML: Record<'app', string> = {
${parts.join('\n')}
}

/** Register the ui:// view as an MCP resource on the given server. */
export function registerUiResources(server: McpServer): void {
  server.registerResource(
    'clearlist-ui-app',
    UI_APP_RESOURCE_URI,
    {
      title: 'ClearList app view',
      description:
        'Interactive view for ClearList tool results: listings gallery, publish success card, and reservations summary.',
      mimeType: UI_RESOURCE_MIME_TYPE,
    },
    async () => ({
      contents: [
        {
          uri: UI_APP_RESOURCE_URI,
          mimeType: UI_RESOURCE_MIME_TYPE,
          text: UI_VIEW_HTML.app,
        },
      ],
    }),
  )
}
`
writeFileSync(join(__dirname, 'register.ts'), out)
process.stdout.write(`register.ts written (${VIEWS.length} views)\n`)
